default_platform(:ios)

platform :ios do
  lane :build_dev do
    desc "Build development version"
    gym(
      scheme: "CounterApp",
      configuration: "Debug",
      clean: true,
      skip_package_ipa: true,  # No crear IPA, solo compilar
      skip_archive: true        # No archivar
    )
  end

  lane :build_release do
    desc "Build release version"
    gym(
      scheme: "CounterApp",
      configuration: "Release",
      clean: true,
      skip_package_ipa: true,  # No crear IPA, solo compilar
      skip_archive: true        # No archivar
    )
  end
end
