export enum TipoNotificacion {
    MENCION_CHAT = 'MENCION_CHAT',
    NUEVO_MENSAJE = 'NUEVO_MENSAJE',
    INSCRIPCION_CURSO = 'INSCRIPCION_CURSO',
    LECCION_COMPLETADA = 'LECCION_COMPLETADA',
    MENSAJE_INSTRUCTOR = 'MENSAJE_INSTRUCTOR',
    CERTIFICADO_OBTENIDO = 'CERTIFICADO_OBTENIDO',
}