export enum PerformanceType {
    QUERY_LENTA = 'QUERY_LENTA',
    COMPLEJIDAD_ALTA = 'COMPLEJIDAD_ALTA',
    RATE_LIMIT_EXCEDIDO = 'RATE_LIMIT_EXCEDIDO',
    PROFUNDIDAD_EXCESIVA = 'PROFUNDIDAD_EXCESIVA',
};
