export enum AuditEventType {
    RATE_LIMIT = 'RATE_LIMIT',
    DATA_ACCESS = 'DATA_ACCESS',
    ADMIN_ACTION = 'ADMIN_ACTION',
    AUTHORIZATION = 'AUTHORIZATION',
    AUTHENTICATION = 'AUTHENTICATION',
    DATA_MODIFICATION = 'DATA_MODIFICATION',
    SECURITY_VIOLATION = 'SECURITY_VIOLATION',
}